//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mid_Demo.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Channel_Table()
        {
            this.Program_Table = new HashSet<Program_Table>();
        }
    
        public int ChannelId { get; set; }
        public string ChannelName { get; set; }
        public int EstablishedYear { get; set; }
        public string Country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Program_Table> Program_Table { get; set; }
    }
}
